# this is how you configure zappr
# a more exhaustive description is at
# https://zappr.readthedocs.io/en/latest/setup

# uncomment this if you want to change anything
approvals:
    pattern: "^lgtm"
    minimum: 1
    ignore: last_committer
   from:
     users:
      - gdemarcsek
      - kepten
      - korsosa
      - mzgaon-prezi
      
